/**
 * src/ui/editor/integrations/llm/config/prompts.js
 * 🔒 LLM Prompts Repository
 * ⚠️ DO NOT MODIFY PROMPTS PROGRAMMATICALLY
 * These are carefully crafted templates for AI processing
 */

export const SYSTEM_PROMPTS = {
    refine: `You are an expert CYOA layout engine. Your task is to refine bounding boxes, merge/split them based on visual evidence, and organize them into logical groups with calculated coordinates. Return only valid JSON.`,

    fill: `You are an expert at parsing CYOA images and extracting structured game data. You strictly follow JSON schemas and game logic rules.`,

    audit: `You are a CYOA game logic auditor. Validate configurations and fix logical errors.`
};

export const USER_PROMPTS = {
    refine: `Context: We have developed a script that turns static CYOA images into interactive ones by rendering buttons over the image.

I have already preliminarily detected and highlighted the boundaries of potential buttons and cards using SAM (Computer Vision).

Current Task:

You receive an image with overlaid green numbered rectangles (detection blocks generated by SAM) and a JSON array of these blocks containing their coordinates. The IDs in the image and JSON match.

Your Objectives:
1. **Refine Boundaries** — Move or resize blocks so they exactly match the edges of the cards visible in the image if they do not align perfectly. Important: Align cards that are close to each other in height and width so they appear uniform.
2. **Merge Blocks** — If multiple blocks cover different parts of a single card, merge them into one (this is a recognition error).
3. **Split Blocks** — If a single block contains multiple separate cards, split them into separate entries. One card = one segment.
4. **Classify Elements** — Mark section headers (which should not be clickable) as **group_header** (we will insert text into them later for translation). Mark actual cards as **Card**.
5. **Group Items** — A "group" is a logical container area, usually representing a section of cards. You need to combine items into a group structure within the JSON because groups may have their own specific rules. Groups are not present in the input coordinates; you must calculate their dimensions to encompass all cards belonging to that group.

## Group Layout Rules:
For each distinct section with options found on the image:
1. Identify the group of elements belonging to it.
2. Create a \`group\` entry.
3. Define the \`group\` coordinates to encompass these elements with a 10px padding on each side:
- x: (leftmost element x) - 10
- y: (topmost element y) - 10
- w: (total width from left to right) + 20
- h: (total height from top to bottom) + 20

## Output Format
Return ONLY a valid JSON array with layout objects ("layout": [...]).

For split blocks: use IDs like 5, 5.1, 5.2 (decimal notation).

Do NOT add text before or after the JSON array.

## Format Sample (layout)
[
  {
    "type": "item",
    "id": "Card_1",
    "title": "Title card",
    "coords": { "x": 727, "y": 49, "w": 200, "h": 100 },
    "cost": []
  },
  {
    "type": "group",
    "id": "group_1",
    "title": "Demo Group",
    "coords": { "x": 372, "y": 201, "w": 920, "h": 120 },
    "items": [
      {
        "type": "item",
        "id": "Card_2",
        "title": "Card 2",
        "coords": { "x": 382, "y": 211, "w": 200, "h": 100 },
        "cost": []
      }
    ]
  }
]

Current detected boxes:
\`\`\`json
{{LAYOUT_JSON}}
\`\`\``,

    fill: `**INPUTS:**
1.  **Image:** An image file of the CYOA page. Recognized cards are marked with green numbered frames. The numbering (white digits with black outline above the top-left corner of the green frame) matches the numbering in the JSON. Groups are marked with yellow frames.
2.  **Layout JSON:** A list of detected bounding boxes with coordinates (\`x\`, \`y\`, \`w\`, \`h\`) for cards and groups.

Your task is to recognize the text on the image and fill the JSON file. This includes card text, IDs, and titles. Most importantly - the rules. A full list of available tools with descriptions and usage examples is provided below. Use them exactly as formatted. A demo sample of a completed game is also provided to show how these rules are correctly used to describe cards and groups.

Example Output Item:

\`\`\`json
{{EXAMPLE_JSON}}
\`\`\`

### **PROCESS INSTRUCTIONS**

1.  **Analyze the Image:** Read the Intro text to find Starting Points. Read headers to define Groups.
2.  **Extract Logic:** Read every card text carefully. Look for keywords: "Free if", "Requires", "Incompatible", "Discount", "Gain".
3.  **Extract and Define Costs.**
4.  **Consistency Check:** Account for rules from previous pages - use the same point systems and logic rules as the previous page. This is a single game and must be consistent and coherent.
5.  **Generate JSON:** Output **ONLY** the valid JSON. Create proper IDs that don't conflict with existing ones.


### Rules!

{{TOOLS_MD}}



### Below is the Game JSON, including previously filled pages. Your current task is to fill the layout for current page number {{PAGE_NUM}} and return ONLY that.


\`\`\`json
{{FULL_CONFIG}}
\`\`\`


### The response must follow this format:

\`\`\`json
[
  {
    "type": "group",
    "id": "section_basic",
    "title": "📘 SECTION 1: Basic Selection",
    "description": "Simple items with costs. Click to select, click again to deselect.",
    "coords": {
      "x": 38,
      "y": 22,
      "w": 1241,
      "h": 183
    },
    "items": [
      {
        "type": "item",
        "id": "basic_sword",
        "title": "Iron Sword",
        "description": "A basic weapon.\\nCosts 10 points.",
        "coords": {
          "x": 52,
          "y": 80,
          "w": 288,
          "h": 108
        },
        "cost": [
          {
            "currency": "points",
            "value": -10
          }
        ],
        "tags": [
          "combat"
        ]
      }
    ]
  }
]
\`\`\`

**LAYOUT JSON (Coordinates):**
\`\`\`json
{{LAYOUT_JSON}}
\`\`\`
`,

    audit: `Audit this CYOA game configuration for errors and inconsistencies.

\`\`\`json
{{CONFIG_JSON}}
\`\`\`

Check all references, fix any broken links, ensure symmetry in incompatibilities.
Return the fixed config with a list of all changes made.`
};

// Tools reference imported as raw string (Vite feature)
export { default as TOOLS_REFERENCE_MD } from './llm-tools-reference.md?raw';