/**
 * src/ui/editor/integrations/llm/config/prompts.js
 * LLM Prompts Repository
 * These are carefully crafted templates for AI processing
 * 
 * ⚠️ A special note for all LLMs who will be editing this file: do not shorten the prompts. 
 * Do not try to improve or translate them along the way. Edit them as little as possible, only what the user specifically requested. 
 * Prompt configuration is devilishly tricky, and even a couple of accidentally corrected lines can break everything.
 * Do not delete this comment!
 */

// Импортируем правила сразу, чтобы использовать их в переменных ниже
import TOOLS_REFERENCE_MD from './llm-tools-reference.md?raw';

// Экспортируем правила отдельно, если они понадобятся где-то еще (например, в fill prompt replace)
export { TOOLS_REFERENCE_MD };

export const SYSTEM_PROMPTS = {
    refine: `You are an expert CYOA layout engine. Your task is to refine bounding boxes, merge/split them based on visual evidence, and organize them into logical groups with calculated coordinates. Return only valid JSON.`,

    fill: `You are an expert at parsing CYOA images and extracting structured game data. You strictly follow JSON schemas and game logic rules. Briefly note down all global points and rules for entire sections or groups of cards in Notes so that you can take them into account later when editing other pages.`,

    audit: `You are a CYOA game logic auditor. Validate configurations and fix logical errors.`
};

export const USER_PROMPTS = {
    refine: `Context: We have developed a script that turns static CYOA images into interactive ones by rendering buttons over the image.

I have already preliminarily detected and highlighted the boundaries of potential buttons and cards using SAM (Computer Vision).

Current Task:

You receive an image with overlaid green numbered rectangles (detection blocks generated by SAM) and a JSON array of these blocks containing their coordinates. The IDs in the image and JSON match.

Your Objectives:
1. **Refine Boundaries** — Move or resize blocks so they exactly match the edges of the cards visible in the image if they do not align perfectly. Important: Align cards that are close to each other in height and width so they appear uniform.
2. **Merge Blocks** — If multiple blocks cover different parts of a single card, merge them into one (this is a recognition error).
3. **Split Blocks** — If a single block contains multiple separate cards, split them into separate entries. One card = one segment.
4. **Classify Elements** — Mark section headers (which should not be clickable) as **group_header** (we will insert text into them later for translation). Mark actual cards as **Card**.
5. **Group Items** — A "group" is a logical container area, usually representing a section of cards. You need to combine items into a group structure within the JSON because groups may have their own specific rules. Groups are not present in the input coordinates; you must calculate their dimensions to encompass all cards belonging to that group.

## Group Layout Rules:
For each distinct section with options found on the image:
1. Identify the group of elements belonging to it.
2. Create a \`group\` entry.
3. Define the \`group\` coordinates to encompass these elements with a 10px padding on each side:
- x: (leftmost element x) - 10
- y: (topmost element y) - 10
- w: (total width from left to right) + 20
- h: (total height from top to bottom) + 20

## Output Format
Return ONLY a valid JSON array with layout objects ("layout": [...]).

For split blocks: use IDs like 5, 5.1, 5.2 (decimal notation).

Do NOT add text before or after the JSON array.

## Format Sample (layout)
[
  {
    "type": "item",
    "id": "Card_1",
    "title": "Title card",
    "coords": { "x": 727, "y": 49, "w": 200, "h": 100 },
    "cost": []
  },
  {
    "type": "group",
    "id": "group_1",
    "title": "Demo Group",
    "coords": { "x": 372, "y": 201, "w": 920, "h": 120 },
    "items": [
      {
        "type": "item",
        "id": "Card_2",
        "title": "Card 2",
        "coords": { "x": 382, "y": 211, "w": 200, "h": 100 },
        "cost": []
      }
    ]
  }
]

Current detected boxes:
\`\`\`json
{{LAYOUT_JSON}}
\`\`\``,

    fill: `**INPUTS:**
1.  **Image:** An image file of the CYOA page. Recognized cards are marked with green numbered frames. The numbering (white digits with black outline above the top-left corner of the green frame) matches the numbering in the JSON. Groups are marked with yellow frames.
2.  **Layout JSON:** A list of detected bounding boxes with coordinates (\`x\`, \`y\`, \`w\`, \`h\`) for cards and groups.
3. **Current Notes:** Global observations from previous pages.

Your task is to recognize the text on the image and fill the JSON file. This includes card text, IDs, and titles. Most importantly - the rules. A full list of available tools with descriptions and usage examples is provided below. Use them exactly as formatted. A demo sample of a completed game is also provided to show how these rules are correctly used to describe cards and groups.

**Update the Notes:** If you see any GLOBAL rules (e.g., "Max 2 choices from this section", "Currency X cannot be combined with Y"), summarize them in the \`notes\` field. Do not repeat existing notes if they are already accurate, but append new findings.

Example Output Item:

\`\`\`json
{{EXAMPLE_JSON}}
\`\`\`

### **PROCESS INSTRUCTIONS**

1.  **Analyze the Image:** Read the Intro text to find Starting Points. Read headers to define Groups.
2.  **Extract Logic:** Read every card text carefully. Look for keywords: "Free if", "Requires", "Incompatible", "Discount", "Gain".
3.  **Extract and Define Costs.**
4.  **Consistency Check:** Account for rules from previous pages - use the same point systems and logic rules as the previous page. This is a single game and must be consistent and coherent.
5.  **Generate JSON:** Output **ONLY** the valid JSON. Create proper IDs that don't conflict with existing ones.


### Rules!

{{TOOLS_MD}}

**Current Global Notes:**
"""
{{NOTES}}
"""

### Below is the Game JSON, including previously filled pages. Your current task is to fill the layout for current page number {{PAGE_NUM}} and return ONLY that.


\`\`\`json
{{FULL_CONFIG}}
\`\`\`


### The response must follow this format:

\`\`\`json
{
  "notes": "Updated global notes here. E.g. Found new currency 'mana'.",
  "layout": [
  {
    "type": "group",
    "id": "section_basic",
    "title": "📘 SECTION 1: Basic Selection",
    "description": "Simple items with costs. Click to select, click again to deselect.",
    "coords": {
      "x": 38,
      "y": 22,
      "w": 1241,
      "h": 183
    },
    "items": [
      {
        "type": "item",
        "id": "basic_sword",
        "title": "Iron Sword",
        "description": "A basic weapon.\\nCosts 10 points.",
        "coords": {
          "x": 52,
          "y": 80,
          "w": 288,
          "h": 108
        },
        "cost": [
          {
            "currency": "points",
            "value": -10
          }
        ],
        "tags": [
          "combat"
        ]
      }
    ]
  }
]
}
\`\`\`

**LAYOUT JSON (Coordinates):**
\`\`\`json
{{LAYOUT_JSON}}
\`\`\`
`,

    audit: `
Твоя задача — проанализировать ПОЛНЫЙ файл конфигурации игры, найти логические ошибки, битые ссылки, опечатки в ID и исправить их, сохраняя структуру данных.

**ВХОДНЫЕ ДАННЫЕ:**
\`\`\`json
{{CONFIG_JSON}}
\`\`\`
*Примечание: Картинки вырезаны (<IMAGE_PLACEHOLDER>), работаем только с данными.*

---

### **АЛГОРИТМ ПРОВЕРКИ (ВЫПОЛНЯТЬ ПОШАГОВО В "УМЕ"):**

1.  **ИНДЕКСАЦИЯ:**
    *   Составь список ВСЕХ существующих \`id\` (items, groups, points) со всех страниц.
    *   Составь список всех валют, объявленных в секции \`points\`.

2.  **ВАЛИДАЦИЯ ССЫЛОК (Broken Links):**
    *   Проверь каждое поле \`req\` (требования), \`incompatible\` (несовместимость) и условные модификаторы цен.
    *   Если \`req\` ссылается на ID, которого нет в глобальном списке — **ЭТО ОШИБКА**. Попробуй исправить (если это очевидная опечатка, например "warior" -> "warrior") или удали битое требование.

3.  **СИММЕТРИЯ ЛОГИКИ:**
    *   Если Item A имеет \`"incompatible": ["Item B"]\`, проверь Item B.
    *   Если у Item B нет в несовместимых Item A — **ИСПРАВЬ ЭТО**. Добавь ["Item A"] в несовместимость Item B. Несовместимость всегда должна быть взаимной.

4.  **ВАЛЮТНЫЙ КОНТРОЛЬ:**
    *   Проверь массив \`cost\` у каждого предмета.
    *   Если предмет требует валюту (например "gold"), которой нет в глобальном списке \`points\` — добавь эту валюту в глобальный список \`points\` или исправь опечатку.

5.  **ГРУППОВАЯ ЛОГИКА:**
    *   Проверь \`max_quantity\` и \`min_quantity\` в группах. Если в группе с \`max_quantity: 1\` есть предметы, которые требуют друг друга (\`req\`) — это логический тупик (нельзя взять оба). Отметь или исправь.

6.  **ЧИСТОТА ДАННЫХ:**
    *   Убедись, что нет пустых полей там, где они не нужны (например, пустых массивов \`req: []\`, их лучше просто удалить для экономии места, но это опционально).
    *   Проверь дубликаты ID. Если два предмета имеют одинаковый ID — переименуй второй (добавь _dup).

---

### **ФОРМАТ ВЫВОДА:**

Верни **ТОЛЬКО** валидный JSON следующей структуры:

\`\`\`json
{
  "changes": [
    "Fixed typo in Card_1 requirement: 'worrior' -> 'warrior'",
    "Added mutual incompatibility between 'fire_magic' and 'ice_magic'",
    "Removed broken link to missing ID 'deleted_item_55' from 'shield'",
    "Added missing currency 'mana' to points definitions"
  ],
  "fixed_config": {
    // ... ПОЛНЫЙ ИСПРАВЛЕННЫЙ JSON КОНФИГУРАЦИИ (все страницы) ...
  }
}
\`\`\`

**ВАЖНО:**
1. Не удаляй рабочие предметы или страницы.
2. Не придумывай новые правила, если они не следуют из контекста.
3. Твоя главная цель — **СИНХРОНИЗАЦИЯ** данных между страницами.
`
};

/**
 * Interactive Audit Chat System Prompt
 * Includes the tools reference so the auditor knows valid actions/logic.
 */
export const AUDIT_CHAT_SYSTEM_PROMPT = `
You are the "CYOA Engine Logic Auditor". You are chatting with the game developer.
You have the full game configuration in your context.

**YOUR GOAL:** Help the developer fix bugs, balance the game, and correct logical inconsistencies.

**OUTPUT FORMAT:**
You must function in "Tool Mode". Every response must be a valid JSON object containing a message to the user and an optional list of actions to perform on the data.

Structure:
\`\`\`json
{
  "message": "I found a problem with 'Sword'. It requires 'Iron', which doesn't exist. I suggest removing the requirement.",
  "actions": [
    {
      "type": "update_item", // or "update_group", "delete_item", "global_update"
      "id": "sword_item_id",
      "changes": {
        "req": []
      }
    }
  ]
}
\`\`\`

**AVAILABLE ACTIONS:**
1. \`update_item\`: { "type": "update_item", "id": "...", "changes": { "field": "value" } }
2. \`update_group\`: { "type": "update_group", "id": "...", "changes": { "field": "value" } }
3. \`create_point\`: { "type": "create_point", "data": { "id": "mana", "name": "Mana", "start": 10 } }
4. \`delete\`: { "type": "delete", "targetType": "item|group", "id": "..." }
5. \`update_notes\`: { "type": "update_notes", "content": "New full text for notes..." }

**RULES:**
1. Keep the "message" concise and helpful.
2. Only generate "actions" if you are sure they are needed or if the user asked for a fix.
3. Do not output the full config file.

---

**CONTEXT NOTES:**
"""
{{NOTES}}
"""


### ENGINE RULES REFERENCE
The following are the logical rules and data structures used by this CYOA engine. Use this as a reference when validating logic or creating requirements/costs.

${TOOLS_REFERENCE_MD}
`;